Add rustls support
ark0f/hyper-socks2 pull request #1
Opened 2019-08-30 13:16 UTC by kinosang

2019-09-04 17:29 UTC, ark0f commented
Is work still in progress?

2019-09-04 17:29 UTC, ark0f commented
Thank you for contribution! Is work still in progress?

2019-09-04 17:30 UTC, kinosang commented
@ark0f yes, there's some problem with webpki, I'm still working on that.

2019-09-06 07:01 UTC, kinosang commented
@ark0f I've tried, but I always got `invalid certificate: UnknownIssuer` error, I cannot solve it.

2019-10-12 09:31 UTC, ark0f requested changes

2019-10-12 09:31 UTC, ark0f commented on Cargo.toml
> +tokio-rustls = { version = "0.9", optional=true }
Add whitspaces between `=`.

2019-10-12 09:31 UTC, ark0f commented on src/lib.rs
> +        let cfg = std::sync::Arc::new(tokio_rustls::rustls::ClientConfig::new());
Add `use` at the top of the function instead of full path.

2019-10-12 09:53 UTC, kinosang commented
@ark0f this pr is still WIP, I'll update asap.

2020-05-12 08:38 UTC, ark0f commented
Done in #2

2020-05-12 08:38 UTC, closed without merging