upgrade to support hyper1
ark0f/hyper-socks2 pull request #14
Opened 2024-01-21 18:33 UTC by aviramha

2024-02-01 04:50 UTC, ark0f requested changes

2024-02-01 04:50 UTC, ark0f commented on Cargo.toml
> +hyper-util = { version = "0.1", features = ["tokio"]}
```suggestion
hyper-util = { version = "0.1", features = ["tokio"] }
```

2024-02-01 04:50 UTC, ark0f commented on src/lib.rs
> +        let mut buf_stream = TokioIo::new(stream); // fixes issue #3
```suggestion
        let mut buf_stream = BufStream::new(TokioIo::new(stream)); // fixes issue #3
```

2024-02-01 04:50 UTC, ark0f commented on Cargo.toml
> +hyper = { version = "1", features = ["server", "http1", "client"] }
It looks like we don't need any of these features

2024-02-01 04:50 UTC, ark0f commented on Cargo.toml
> +hyper-util = { version = "0.1", features = ["http1", "client", "client-legacy"]}
```suggestion
hyper-util = { version = "0.1", features = ["http1", "client", "client-legacy"] }
```

2024-02-01 06:16 UTC, aviramha commented on Cargo.toml
> +hyper-util = { version = "0.1", features = ["tokio"]}
Done

2024-02-01 06:21 UTC, aviramha commented on src/lib.rs
> +        let mut buf_stream = TokioIo::new(stream); // fixes issue #3
this leads to
```
mismatched types
expected associated type `<C as tower_service::Service<Uri>>::Response`
            found struct `TokioIo<<C as tower_service::Service<Uri>>::Response>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B4%5D?4#file%3A%2F%2F%2FUsers%2Faviramhassan%2FCode%2Fhyper-socks2%2Fsrc%2Flib.rs)
lib.rs(168, 9): arguments to this enum variant are incorrect
lib.rs(168, 9): the type constructed contains `TokioIo<<C as tower_service::Service<Uri>>::Response>` due to the type of the argument passed
result.rs(506, 5): tuple variant defined here
```

2024-02-01 06:23 UTC, aviramha commented
Thanks for the review. I think I resolved all comments.

2024-02-02 04:51 UTC, ark0f approved these changes
Thank you for contribution

2024-02-02 04:51 UTC, merged